---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ovh-checker-<ENV>-redis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /media/k8s/ovh-checker-<ENV>-redis
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovh-checker-<ENV>-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
