---
name: Docker
"on": [push]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v1
      - name: Check
        run: |
          make deps
          make lint
  test:
    needs: check
    runs-on: ubuntu-18.04
    services:
      db:
        image: postgres:9.6
        env:
          POSTGRES_DB: ovh_test
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: runner
        ports:
          - 5432:5432
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v1
      - name: Test
        run: make test
  docker:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          make docker
          make push
